name: Generate and Commit Metadata

on:
  push:
    branches:
      - main    # ← adjust if needed

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Generate metadata.json
        run: npm run metadata

      - name: Commit and push metadata
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Force-add so .gitignore is overridden
          git add -f resources/metadata.json
          if ! git diff --cached --quiet; then
            git commit -m "ci: update build metadata [skip ci]"
            git push
          else
            echo "No changes to metadata.json"
          fi
